### PR TITLE
Fix import

### PR DESCRIPTION
**Pull request by UrsZeidler**
Add two other import options: 

```
import * as x from "url";    
import {a as b, c as d} from "url" ;
```

Changed the import property url to importURI. Hopefully this can be used to filter the scope later on.

I'm not sure if this is the elegant solution, the ImportDirective look a bit messy to me now. (Lack of experience maybe.)

### CODE REVIEW

**Comment by webdaford** [comment]
I got some time yesterday to glance at the code and restart my 
development environment for the project.  Then, I ran into a snag, the 
Maven build went just fine, but Eclipse is complaining about missing 
dependencies.  I ran out of time to fix things; I expect it's because I 
upgraded to 4.5.2 recently and I do some local caching of the Eclipse 
repositories to speed up my builds.  There's probably a mismatch that 
will be resolved when I update the cached copies I keep.  At least 
that's my working theory.  Eclipse is great, except when it isn't.

Dan

**Comment by UrsZeidler** [comment]
Yeah, p2.

It Came from Beneath ...

p2_came_from_beneath_equinox

**Comment by webdaford** [comment]
I thought I was the only one stared at p2 and wondered "Why?"  Thanks for the fix.  I don't think this was overlooked when I first created the Xtext grammar.  I expect it's been added since.  Dan

**Comment by UrsZeidler** [comment]
>  I don't think this was overlooked when I first created the Xtext grammar. I expect it's been added since.

It was. In the 0.2.1 release of the compiler.
https://github.com/ethereum/wiki/wiki/Solidity-Changelog
It is really a pity that they don't work with and therefore update their grammar,txt.

> I thought I was the only one stared at p2 and wondered "Why?

I once filed this bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=242187
The highlight was this comment (https://bugs.eclipse.org/bugs/show_bug.cgi?id=242187#c10):

> This is indeed not a file to be interpreted by mere mortals. Typically we just pass these files on to a crack team of espresso-toting French academics who go off muttering about poorly defined optimization functions and eventually come back with a new wad of symbols to throw in the file.

have a nice day, greetings Urs.

**Pull request merged**
