### PR TITLE
fixed the new statement

### PR DESCRIPTION
**Pull request by UrsZeidler**
Also a minor grammar fix.

Instantiation of a contract need to accept the parenthesis and the parameters.

```
 blogs[blogCount] = new ShortBlog;
```

Is illegal but accepted while

```
blogs[blogCount] = new ShortBlog();
```

is correct but not accepted.

### CODE REVIEW

**Comment by webdaford** [comment]
Thanks

**Comment by UrsZeidler** [comment]
Did you close this intentionally or accidentally?

Btw, would you mind to enable the issues ? 
I think we could plan the progress and features a bit better.

**Comment by webdaford** [comment]
Accident.  Issues enabled.
Dan

**Comment by UrsZeidler** [comment]
Could you reopen and merge it? I have removed the branch from my branch list.

**Comment by webdaford** [comment]
I'm running into an error reopening as the branch is deleted.

**Comment by UrsZeidler** [comment]
Same for me, as I had to switch the fork from the original dell repository to your repository.
New as #15.

**Pull request closed without merging**
