### PR TITLE
Add this statement

### PR DESCRIPTION
**Pull request by UrsZeidler**
Added the super and this statements, also provide proposals for 'this', 'super', members and member variables.

I'm not perfect sure if the solution is in the way xText is used.
Maybe you take a closer look.

### CODE REVIEW

**Comment by webdaford** [comment]
Everything builds fine in Maven, but I'm getting 2 compilation errors from Eclipse in SolidityProposalProvider.xtend   It doesn't like "override", lines 57 and 103.

e.g.
The method completeSuperExpression_FieldOrMethod(EObject, Assignment, ContentAssistContext, ICompletionProposalAcceptor) of type SolidityProposalProvider must override a superclass method.    SolidityProposalProvider.xtend  /com.dell.research.bc.eth.solidity.editor.ui/src/com/dell/research/bc/eth/solidity/editor/ui/contentassist  line: 103 /com.dell.research.bc.eth.solidity.editor.ui/src/com/dell/research/bc/eth/solidity/editor/ui/contentassist/SolidityProposalProvider.xtend Xtend Problem

Do you see these as well?

**Comment by UrsZeidler** [comment]
No, maybe you need to "Generate Language Infrastructure (com.dell.research.bc.eth.solidity.editor)" 
You should find the methods in com.dell.research.bc.eth.solidity.editor.ui.contentassist.AbstractSolidityProposalProvider, if not you need to regenerate.

**Comment by UrsZeidler** [comment]
closed for #11

**Comment by webdaford** [comment]
Yup. That fixed it.  Merged.

**Comment by webdaford** [comment]
I left this on Sunday to process this week.  I didn't interpret the "closed for #11" as instructions to not merge this branch in.  Mistake.  I've tried to revert, but git refuses. Can you figure out a correction?

**Comment by webdaford** [comment]
I left this on Sunday to process this week.  I didn't interpret the "closed for #11" as instructions to not merge this branch in.  Mistake.  I've tried to revert, but git refuses. Can you figure out a correction?

**Comment by webdaford** [comment]
reopen

**Comment by UrsZeidler** [comment]
It was not very good communicated. I thought when I close the merge you are not able to pull it.
I will patch this on to of this branch.
Pity that the revert not work.

**Comment by webdaford** [comment]
reopen

**Comment by webdaford** [comment]
reopen

**Pull request closed without merging**
